In [2]:
import numpy as np
import pandas as pd
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score

# Read the training and test datasets
train_df = pd.read_csv('C:\\Users\\Robert\\Documents\\Development\\VS_Code\\data_input\\cc_train.csv')
test_df = pd.read_csv('C:\\Users\\Robert\\Documents\\Development\\VS_Code\\data_input\\cc_test.csv')

# Replace all blank, null or NaN values to that columns' Mean value
train_df = train_df.fillna(train_df.mean())
# Replace all blank, null or NaN values to that columns' Mean value
test_df = test_df.fillna(test_df.mean())

# Split the training dataset into features and target
X_train = train_df.drop('Credit_Score_Number', axis=1)
y_train = train_df['Credit_Score_Number'] - 1  # Subtract 1 from the target labels
y_test = test_df['Credit_Score_Number'] - 1  # Subtract 1 from the target labels

# ensure same number of columns
test_df = test_df.drop('Credit_Score_Number', axis=1)

X = train_df.drop('Credit_Score_Number', axis=1)
y = train_df['Credit_Score_Number'] - 1  # Subtract 1 from the target labels

# Split data into training and testing sets (70% training, 30% testing)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Train the XGBoost classifier
xgb_classifier = XGBClassifier(use_label_encoder=False, eval_metric="logloss")
xgb_classifier.fit(X_train, y_train)

# Make predictions on the test set
y_pred = xgb_classifier.predict(X_test)

# Evaluate the classifier
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)
print("Classification report:\n", classification_report(y_test, y_pred))
print("Confusion matrix:\n", confusion_matrix(y_test, y_pred))
recall = recall_score(y_test, y_pred, average='weighted')
precision = precision_score(y_test, y_pred, average='weighted')
f1 = f1_score(y_test, y_pred, average='weighted')

    # Print evaluation metrics
#print(f"{name}:")
print(f"  Accuracy: {accuracy:.2f}")
print(f"  Recall: {recall:.2f}")
print(f"  Precision: {precision:.2f}")
print(f"  F1 score: {f1:.2f}\n")


c:\Users\Robert\Anaconda3\lib\site-packages\xgboost\sklearn.py:1395: UserWarning: `use_label_encoder` is deprecated in 1.7.0.
  warnings.warn("`use_label_encoder` is deprecated in 1.7.0.")


Accuracy: 0.7446584161163217
Classification report:
               precision    recall  f1-score   support

           0       0.75      0.72      0.73      5194
           1       0.76      0.79      0.78      9600
           2       0.67      0.66      0.67      3225

    accuracy                           0.74     18019
   macro avg       0.73      0.72      0.73     18019
weighted avg       0.74      0.74      0.74     18019

Confusion matrix:
 [[3719 1299  176]
 [1176 7559  865]
 [  53 1032 2140]]
  Accuracy: 0.74
  Recall: 0.74
  Precision: 0.74
  F1 score: 0.74

